name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    name: Run Cypress Tests              # Display name for the job
    runs-on: ubuntu-latest

  # Define a matrix strategy to run tests on multiple browsers
    strategy:
      matrix:
       browser: [chrome, edge]         # Run tests on Chrome and Edge
    

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Run Cypress tests
      - name: Run Cypress Tests
        run: npx cypress run

      # Set executable permissions for Cypress binary
      - name: Grant Permissions
        run: chmod +x ./node_modules/.bin/cypress

      # Upload Cypress artifacts (videos and screenshots) in case of failure
      - name: Upload Cypress Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: cypress/videos, cypress/screenshots

      # Publish test results
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/results

      # Step 7: Save test results as artifacts
      - name: Archive Mochawesome Report
        if: always()                    # Run this step regardless of test results
        uses: actions/upload-artifact@v3
        with:
              # Create unique artifact name using browser and commit SHA
            name: mochawesome-report-${{ matrix.browser }}-${{ github.sha }}
            path: cypress/reports/        # Location of test reports